### ISSUE TITLE
warning: failed to read collections cache: FileNotFoundError(2, 'No such file or directory')

### ISSUE THREAD

**Issue by thefinn12345** [a-tal/gab#1]
Not sure if this program is being looked at anymore. Perhaps it's too old or something has changed on gab's end?

**Comment by Ryochan7** [comment]
Gab moved to using a Mastodon based system back around July 2019 IIRC. This project was written for the old Gab site API. Unfortunately, you cannot use the Python Mastodon API package since it actively blocks connections to several Gab Social instances. You need to either patch the library or use a modified version. I host a forked version that removes the block but I have not updated it in a while; it still works on the site.

https://github.com/Ryochan7/Mastodon.py

Making a bot for Mastodon is fairly simple once you get a proper library. Here is a decent tutorial on how to make a bot that will work with Mastodon instances.

https://shkspr.mobi/blog/2018/08/easy-guide-to-building-mastodon-bots/

Also, here is an example of an active bot that I use with Gab and the BotsInSpace Mastodon instance. It is a bot that takes an NIST randomness beacon and posts a Bible passage based on the number that is obtained.

https://gitlab.com/ryochan7/nistbot-mastodon

**Comment by thefinn12345** [comment]
Wow, that's brilliant... it's exactly the use I wanted to put this to ;)

**Comment by a-tal** [comment]
thanks @Ryochan7

**Comment by Ryochan7** [comment]
Looks like it doesn't matter now. It seems Torba removed support for the Mastodon API endpoint and third party app support. It is now impossible to make a bot account on Gab. The last post my bot made was dated 2020/12/22 and the Gab API Developers group confirms that the breakage was intentional. Supposedly Mammudeck will be allowed again at some point but nothing else. RIP @NIST_Oracle bot.
